### ISSUE TITLE
Installation Problem: 'command' not recognized

### ISSUE THREAD

**Issue by gruenemuetze** [ivanproskuryakov/Aisel#20]
I'm having troubles installing AIsel: AIsel:install
 
Eventhough I'm having some troubles with the installation. Aisle:install fails with the message that bower is required. But it is installed. See printscreen for more info:

![printscreen](https://cloud.githubusercontent.com/assets/13075514/8391394/fdddc94e-1cc2-11e5-8232-d072ef45aae2.png)

**Comment by ivanproskuryakov** [comment]
@gruenemuetze do you have http://bower.io/ on your machine ?

**Comment by gruenemuetze** [comment]
@ivanproskuryakov yes, if I run it from the command line it works. See printscreen

**Comment by ivanproskuryakov** [comment]
@gruenemuetze sorry, didn't realise that you on windows
Installer runs ```sh bower.sh``` which is a shell script

https://github.com/ivanproskuryakov/Aisel/blob/master/bower.sh

Do it manually then, with following:

```
1. composer 
composer install
2. database 
php app/console doctrine:database:drop
php app/console doctrine:database:create
php app/console doctrine:schema:create
php app/console doctrine:fixtures:load
3. bower
manually, check contests of bower.sh
```

**Comment by gruenemuetze** [comment]
Thanks for you quick reply. It worked. But now I can't access the backend. The user table is emtpy. How can I setup the initial user?

**Comment by ivanproskuryakov** [comment]
load fixtures with:
```
php app/console doctrine:fixtures:load
```

You may use following users:
Frontend demo: http://ecommerce.aisel.co/en/ [frontenduser/frontenduser]
Backend demo: http://admin.ecommerce.aisel.co/ [backenduser/backenduser]

**Comment by ivanproskuryakov** [comment]
@gruenemuetze how is it going, did you solve your question ?

**Comment by manoj815** [comment]
Hi I manually flow all above step but how to run in windows host i also created a virual host named 
```
<VirtualHost aisel.dev:80>
	DocumentRoot "D:\xampp\htdocs\Aisel-master\Aisel"
	ServerName aisel.dev
</VirtualHost>
```
But how to run i browser
