### ISSUE TITLE
error install cms

### ISSUE THREAD

**Issue by enri90** [ivanproskuryakov/Aisel#55]
![aisel](https://cloud.githubusercontent.com/assets/2630335/12377959/57bb7d1e-bd2f-11e5-8a14-028eb6d05364.png)

Notice: Use of undefined constant CURLOPT_FORBID_REUSE - assumed 'CURLOPT_F  
  ORBID_REUSE'

**Comment by ivanproskuryakov** [comment]
Hello @enri90, make sure that curl extension is installed on your host

```sh

➜  www git:(master) php -m | grep curl
curl

```

**Comment by enri90** [comment]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/curl.so' - /usr/lib/php5/20121212/curl.so: cannot open shared object file: No such file or directory in Unknown on line 0

I have a virtualmin ubuntu for the project but I can not solve this problem

**Comment by enri90** [comment]
using a normal account are able to enter admin management should be limited you selling and admin

**Comment by ivanproskuryakov** [comment]
A.
you have curl on your linux machine, but what shows **echo phpinfo();** do you have curl extension enabled ?
to add: you may try to work with Aisel through vagrant, just cd to project and type "vagrant up", let me know if it works.

B.
- regarding admin, we are planning to user the same UI for sellers and administrators, API endpoints and security rules are different
https://github.com/ivanproskuryakov/Aisel/blob/master/Aisel/app/config/security.yml#L25-L26

**Comment by enri90** [comment]
![vagrant](https://cloud.githubusercontent.com/assets/2630335/12378487/888b6b9c-bd3f-11e5-872b-e50b89b63ed5.png)

I tried with vagrant but not knowing I'm stuck here
