### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by enri90** [ivanproskuryakov/Aisel#58]
The idea is not bad but it would be nice to have a way to add new languages?

You can remove the reference language in the url?

In settings management language is fantastic would be replicated
in pages and products with the ability to enable and disable
also cleaning the list page and products

![image](https://cloud.githubusercontent.com/assets/2630335/12378788/c16d313e-bd49-11e5-984f-51891b03cb48.png)

**Comment by ivanproskuryakov** [comment]
Aisel's api designed to have {locale} parameter in URL, but it could be change on frontend. Currently we don't have translations for labels, buttons and messages. I'm planning to add it later

**Comment by enri90** [comment]
if I knew how to make you helped
