### ISSUE TITLE
addProductToCart button

### ISSUE THREAD

**Issue by enri90** [ivanproskuryakov/Aisel#59]
![image](https://cloud.githubusercontent.com/assets/2630335/12378833/14e56f38-bd4b-11e5-839d-0bea48f8b111.png)

does not work Add to Cart :(

**Comment by ivanproskuryakov** [comment]
@enri90 master still in development, I'm apologies for these issues

**Comment by enri90** [comment]
I wait anxiously

**Comment by ivanproskuryakov** [comment]
@enri90 admin users cant add products to cart, please try with *user@asel.co* user password *user*
