### ISSUE TITLE
user to access backend

### ISSUE THREAD

**Issue by enri90** [ivanproskuryakov/Aisel#60]
![image](https://cloud.githubusercontent.com/assets/2630335/12379727/4e460c78-bd60-11e5-923b-3b63a47d8818.png)

as you can never be normal user access to the backend?

**Comment by ivanproskuryakov** [comment]
Application goal is to give all frontend users ability to sell products. Aisel will be designed to share UI controls between ADMIN user and SELLER users

**Comment by enri90** [comment]
you can make a setting to choose from admin to decide who permits user sellers?

**Comment by ivanproskuryakov** [comment]
@enri90 yes, I will be done in nearest future.
