### ISSUE TITLE
syntax error unexpected 'class' 

### ISSUE THREAD

**Issue by enri90** [ivanproskuryakov/Aisel#64]
Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/project/public_html/src/Aisel/UserBundle/Manager/UserManager.php on 260

php v 5.4.45

it depends on the version of php?

**Comment by shhfrlsk06** [comment]
Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

same here,, try to debug but it shown the error on bower component/ angularjs

**Comment by shhfrlsk06** [comment]
you need to use PHP 5.5 and above.
