### ISSUE TITLE
Gruntfile

### ISSUE THREAD

**Issue by enri90** [ivanproskuryakov/Aisel#68]
grunt Gruntfile.js  
Warning: Task "Gruntfile.js" not found. Use --force to continue.                                                                                                            

Aborted due to warnings.                                                                                                                                                    

Execution Time (2016-03-15 23:58:29 UTC)  
loading tasks  7ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 88%  
Total 8ms

**Comment by ivanproskuryakov** [comment]
@enri90 make sure that you have grunt on your machine.
 - make sure that you are running ''grunt" in "Aisel" directory.
 - install npm packages for grunt with the command: "npm install"

<img width="910" alt="screen shot 2016-03-19 at 12 47 29 pm" src="https://cloud.githubusercontent.com/assets/3517364/13897842/c47808e2-edd0-11e5-89aa-6f3622fc2f77.png">
