### ISSUE TITLE
installation missing command

### ISSUE THREAD

**Issue by piotr-galas** [ivanproskuryakov/Aisel#7]
To install aplication we should run: 

          php app/console aisel:install

But this command doesn't exist.

**Comment by ivanproskuryakov** [comment]
I think I removed this command.

Try 0.0.1 release
https://github.com/ivanproskuryakov/Aisel/releases/tag/v0.1.0

If I can be of any further assistance, please let me know.
Sincerely, Ivan.

.........................................................................
LinkedIn*: *www.linkedin.com/pub/ivan-proskuryakov/31/200/316
E-mail: service@magazento.com
This message and any associated files is intended only for the use of the
individual or entity to which it is addressed and may contain information
that is confidential, subject to copyright or constitutes a trade secret.
If you are not the intended recipient you are hereby notified that any
dissemination, copying or distribution of this message or files associated
with this message is strictly prohibited. If you have received this message
in error, please notify us immediately.

**Comment by razzaghi** [comment]
how can install and create database without this command?
